pipeline {
    agent any

    tools {
        maven 'Maven'
    }

    stages {

        stage('Build Jar') {
            steps {
                dir('demo-app') {
                    sh 'mvn clean package'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('demo-app') {
                    sh 'docker build -t maven-demo-app .'
                }
            }
        }

        stage('Stop Old Container') {
            steps {
                sh 'docker rm -f demo-container || true'
            }
        }

        stage('Run New Container') {
            steps {
                sh 'docker run -d -p 8080:8080 --name demo-container maven-demo-app'
            }
        }
    }
}
