pipeline {
    agent any

    tools {
        maven 'Maven'
    }

    stages {

        stage('Build') {
            steps {
                dir('demo-app') {
                    sh 'mvn clean package'
                }
            }
        }

        stage('Run') {
            steps {
                dir('demo-app') {
                    sh 'nohup java -jar target/*.jar &'
                }
            }
        }
    }
}
